apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: inoti.ptrps.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openwebui-service
            port:
              number: 80
  - host: admin.ptrps.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: middleware-service
            port:
              number: 8080
